[package]
name = "play-async"
version = "0.1.0"
authors = ["rustcargo <rustcargo@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
hyper = "0.12"