[package]
name = "exercises"
version = "0.1.0"
authors = ["rustcargo <rustcargo@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
play_str = { path = "play_str" }
play_thread = { path = "play_thread" }